
[Miscellaneous]
	#When a Wear requirement is not met, should the item be dropped?
	alwaysDropWornItems = false
	#Should the Welcome message come up?
	showWelcome = true
	#Should your personal Donator Welcome message come up?
	showPatreonWelcome = true
	#Should certain items be restricted from being crafted, without the level requirement?
	craftReqEnabled = true

["Vein Mining"]
	#Every how many levels does 1 charge become worth +1 hardness? (If this is set to 32, your level is 50, and you have 64 charge, you can vein (50 / 160) * 320 = 100 hardness worth of blocks, which is 2.0 Obsidian, or 33.3 Coal Ore)
	#Range: 0.01 ~ 10000.0
	levelsPerHardnessMining = 160.0
	#Should veining wood material blocks start from the highest block?
	veinWoodTopToBottom = true
	#How many blocks max can be veined?
	#Range: 1 ~ 1000000
	veinMaxBlocks = 10000
	#What is the lowest hardness for each block veined? (Crops have 0 hardness, this makes crops not infinitely veined)
	#Range: 0.0 ~ 10000.0
	minVeinHardness = 0.5
	#Every how many levels does 1 charge become worth +1 hardness? (If this is set to 16, your level is 50, and you have 64 charge, you can vein (50 / 320) * 320 = 50 hardness worth of ground, which is 100 Dirt)
	#Range: 0.01 ~ 10000.0
	levelsPerHardnessExcavation = 320.0
	#How much hunger should be exhausted per block veined?
	#Range: 0.0 ~ 20.0
	exhaustionPerBlock = 0.2
	#Should a succesful sleep recharge every player currently in that world Vein Charge?
	sleepRechargesWorldPlayersVeinCharge = true
	#Every how many levels does 1 charge become worth +1 hardness? (If this is set to 80, your level is 50, and you have 320 charge, you can vein (50 / 80) * 320 = 200 hardness worth of Crafting Related (Such as wool, carpet, bed) blocks, which depends on how hard they are)
	#Range: 0.1 ~ 10000.0
	levelsPerHardnessCrafting = 160.0
	#Is vein mining allowed? true = on, false = off
	veiningAllowed = true
	#How much is the lowest cost for each block veined? (1 = 1 charge, 1 charge regens per second)
	#Range: 0.01 ~ 10000.0
	minVeinCost = 0.5
	#How much vein charge can a player hold at max? (1 recharges every second)
	#Range: 0.0 ~ 100000.0
	maxVeinCharge = 320.0
	#What is the maximum distance a player's vein can reach?
	#Range: 1.0 ~ 1000.0
	veinMaxDistance = 1000.0
	#Every how many levels does 1 charge become worth +1 hardness? Plants have no hardness, but there is a minimum hardness while veining config in here, which is 0.5 by default, making it 200 plants at level 50 farming, with 320 charge, if this is set to 160
	#Range: 0.1 ~ 10000.0
	levelsPerHardnessFarming = 160.0
	#How many blocks get broken every tick?
	#Range: 1 ~ 10000
	veinSpeed = 1
	#Should players be allowed to vein blocks that they did not place?
	veiningOtherPlayerBlocksAllowed = false
	#Every how many levels does 1 charge become worth +1 hardness? (If this is set to 32, your level is 50, and you have 64 charge, you can vein (50 / 160) * 320 = 100 hardness worth of logs, which is 50 Logs)
	#Range: 0.01 ~ 10000.0
	levelsPerHardnessWoodcutting = 160.0

["Mob Scaling"]
	#What is the maximum amount an aggressive mob's speed will be boosted?
	#Range: 0.0 ~ 100.0
	maxMobSpeedBoost = 10.0
	#What is the maximum amount an aggressive mob's HP will be boosted?
	#Range: 0.0 ~ 1024.0
	maxMobHPBoost = 1000.0
	#Should mob xp multipliers inside of biomes be enabled? False means no multipliers
	biomeMobMultiplierEnabled = true
	#How much an aggresive mob's HP will increase per one Power Level?
	#Range: 0.0 ~ 100.0
	mobHPBoostPerPowerLevel = 5.0
	#How much an aggresive mob's speed will increase per one Power Level?
	#Range: 0.0 ~ 10.0
	mobSpeedBoostPerPowerLevel = 1.0
	#What is the maximum amount an aggressive mob's damage will be boosted?
	#Range: 0.0 ~ 1000.0
	maxMobDamageBoost = 100.0
	#How much an aggresive mob's damage will increase per one Power Level?
	#Range: 0.0 ~ 10.0
	mobDamageBoostPerPowerLevel = 1.0

[Requirements]
	#Should mob kill xp be enabled? False means no requirements
	killXpEnabled = true
	#Is catching items from Fish Pool while Fishing enabled? False = off
	fishPoolEnabled = true
	#Should xp values for general things be enabled? (Such as catching fish)
	xpValueGeneralEnabled = true
	#Is Salvaging items using the Repairing skill enabled? False = off
	salvageEnabled = true
	#Should wear requirements be enabled? False means no requirements
	wearReqEnabled = true
	#Should weapon requirements be enabled? False means no requirements
	weaponReqEnabled = true
	#Main held items xp multiplier enabled? False = off
	heldItemXpBoostEnabled = true
	#worn items xp boost enabled? False = off
	wornItemXpBoostEnabled = true
	#Should fished items have a chance at being Enchanted? enabled? False = off
	fishEnchantPoolEnabled = true
	#Should plants be enabled? False means no extra chance
	plantEnabled = true
	#Should break requirements be enabled? False means no requirements
	breakReqEnabled = true
	#Should ores be enabled? False means no extra chance
	oreEnabled = true
	#Should mob kill req be enabled? False means no requirements
	killReqEnabled = true
	#Should xp values for breaking things first time be enabled? False means only Hardness xp is awarded for breaking
	xpValueBreakingEnabled = true
	#Commands being fired on specific level ups enabled? False = off
	levelUpCommandEnabled = true
	#Should biome requirements be enabled? False means no requirements
	biomeReqEnabled = true
	#Should logs be enabled? False means no extra chance
	logEnabled = true
	#Should use requirements be enabled? False means no requirements
	useReqEnabled = true
	#Should mob rare drops be enabled? False means no requirements
	mobRareDropEnabled = true
	#Should xp multipliers be enabled? False means no multipliers
	biomeXpBonusEnabled = true
	#Should biome negative effects be enabled? False means no negative effects
	biomeEffectEnabled = true
	#Should tool requirements be enabled? False means no requirements
	toolReqEnabled = true
	#Should place requirements be enabled? False means no requirements
	placeReqEnabled = true
	#Should config from default_data.json be loaded? False means only data.json is loaded
	loadDefaultConfig = true

[Levels]
	#What is the global max level
	#Range: 1 ~ 1000000
	maxLevel = 999
	#Every how many levels should a level up broadcast be sent to all players? (10 = every 10 levels)
	#Range: 1 ~ 1000000
	levelsPerMilestone = 10
	#Should fireworks appear on Milestone level up, to other players?
	milestoneLevelUpFirework = true
	#What is the xp increase per level ( baseXp + level * xpPerLevel )
	#Range: 1 ~ 1000000
	xpIncreasePerLevel = 50
	#Should every 10th level up be broadcast to everyone?
	broadcastMilestone = true
	#Should a player have all their skills wiped to level 1 upon death?
	wipeAllSkillsUponDeathPermanently = false
	#Should fireworks appear on level up?
	levelUpFirework = true
	#What is the baseXp to reach level 2 ( baseXp + level * xpPerLevel )
	#Range: 1 ~ 1000000
	baseXp = 250

[Multipliers]
	#How much xp everyone gains on Peaceful Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	peacefulMultiplier = 0.3333333333333333
	#How much xp everyone gains in Flying (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	flyingMultiplier = 1.0
	#How much xp everyone gains in Swimming (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	swimmingMultiplier = 1.0
	#How much xp everyone gains on Easy Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	easyMultiplier = 0.6666666666666666
	#How much xp everyone gains on Hard Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	hardMultiplier = 1.3333333333333333
	#How much xp everyone gains in Repairing (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	smithingMultiplier = 1.0
	#How much xp everyone gains in Mining (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	miningMultiplier = 1.0
	#How much xp everyone gains in Building (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	buildingMultiplier = 1.0
	#How much of the xp above whole level you loose (1 = 100% = from 5.5 to 5.0, 0.5 = 50% = from 5.5 to 5.25
	#Range: 0.0 ~ 1.0
	deathXpPenaltyMultiplier = 1.0
	#How much xp everyone gains on Normal Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	normalMultiplier = 1.0
	#How much xp everyone gains in Farming (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	farmingMultiplier = 1.0
	#How much xp everyone gains in Agility (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	agilityMultiplier = 1.0
	#How much xp everyone gains in Excavation (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	excavationMultiplier = 1.0
	#How much xp everyone gains in Archery (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	archeryMultiplier = 1.0
	#How much xp everyone gains in Crafting (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	craftingMultiplier = 1.0
	#How much xp you get in biomes you do not meet the requirements for (1 = Full xp, 0.5 = Half xp)
	#Range: 0.0 ~ 1.0
	biomePenaltyMultiplier = 0.5
	#How much xp everyone gains in Fishing (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	fishingMultiplier = 1.0
	#How much xp everyone gains in Endurance (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	enduranceMultiplier = 1.0
	#How much xp everyone gains in Combat (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	combatMultiplier = 1.0
	#How much xp everyone gains (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	globalMultiplier = 1.0
	#How much xp everyone gains in Woodcutting (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	woodcuttingMultiplier = 1.0

[GUI]
	#When a screenshot is taken upon levelling up, should the skills list turn on automatically to be included in the screenshot?
	lvlUpScreenshotShowSkills = false
	#Should the Xp left indicator always be on? false = only appears with Show GUI key
	xpLeftDisplayAlwaysOn = false
	#If Off, xp drops will no longer stack with each other
	stackXpDrops = true
	#GUI Xp drops position X (Width)
	#Range: 0.0 ~ 100.0
	xpDropOffsetX = 0.5
	#Should xp drops sync up with the bar being open or closed? HIGHLY RECOMMEND TO KEEP FALSE IF YOU ARE MOVING XP DROP POSITIONS
	xpDropsAttachedToBar = true
	#GUI Xp drops position Y (Height, 0 is top, 1 is bottom (1 is probably invisible due to clipping) )
	#Range: 0.0 ~ 1.0
	xpDropOffsetY = 0.0
	#How far away does the Xp Drop spawn
	#Range: 0.0 ~ 1000.0
	xpDropSpawnDistance = 50.0
	#GUI bar position Y (Height, 0 is top, 1 is bottom (1 is probably invisible due to clipping) )
	#Range: 0.0 ~ 100.0
	barOffsetY = 0.0
	#GUI bar position X (Width)
	#Range: 0.0 ~ 100.0
	barOffsetX = 0.5
	#If Off, xp drops will no longer appear
	showXpDrops = true
	#At what age do xp drops start to decay?
	#Range: 0.0 ~ 5000.0
	xpDropDecayAge = 350.0
	#How opaque (visible) can the xp drop get?
	#Range: 0.0 ~ 255.0
	xpDropMaxOpacity = 200.0
	#GUI bar position Y (Height, 0 is top, 1 is bottom (1 is probably invisible due to clipping) )
	#Range: 0.0 ~ 100.0
	veinBarOffsetY = 0.65
	#Should a screenshot be taken everytime you level up?
	lvlUpScreenshot = false
	#GUI bar position X (Width)
	#Range: 0.0 ~ 100.0
	veinBarOffsetX = 0.5
	#Should the Xp Bar always be on? false = only appears while holding Show GUI or when you gain xp
	xpBarAlwaysOn = false
	#How much out of MaxOpacity does the Xp Drop become visible per 1 distance
	#Range: 0.0 ~ 255.0
	xpDropOpacityPerTime = 5.0
	#What is the minimum amount xp grows a set amount of time? (Default 0.2, increase to speed up growth)
	#Range: 0.01 ~ 100.0
	minXpGrow = 1.0

["Breaking Speed"]
	#How many blocks it takes to reach 0 Break Speed (will get capped by Minimum Breaking Speed)
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	blocksToUnbreakableY = 1000.0
	#How much your cutting speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	woodcuttingBonusSpeed = 1.0
	#How much your farming speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	farmingBonusSpeed = 1.0
	#How much your digging speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	excavationBonusSpeed = 1.0
	#Minimum Breaking Speed (1 is Original speed, 0.5 is half)
	#Range: 0.0 ~ 100.0
	minBreakSpeed = 0.5
	#How much your mining speed increases per level (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	miningBonusSpeed = 1.0

[Mining]
	#Hardest considered block (1 hardness = 1 remove xp. 0 = no xp for block hardness, 30 means obsidian caps at 30xp per block.)
	#Range: 0.0 ~ 1000000.0
	blockHardnessLimitForBreaking = 250.0

[Building]
	#Every how many levels you gain an extra block of reach
	#Range: 0.0 ~ 1000.0
	levelsPerOneReach = 25.0
	#Hardest considered block (1 hardness = 1 build xp. 0 = no xp for block hardness, 30 means obsidian caps at 30xp per block.)
	#Range: 0.0 ~ 1000000.0
	blockHardnessLimitForPlacing = 250.0
	#What is the maximum reach a player can have
	#Range: 0.0 ~ 1000.0
	maxExtraReachBoost = 20.0

[Farming]
	#Do players get xp for breeding animals?
	breedingXpEnabled = true
	#How much xp should be awarded in Farming for breeding two animals? (Json Overrides this) (Set to 0 to disable default xp)
	#Range: 0.0 ~ 1000000.0
	defaultBreedingXp = 10.0

[Agility]
	#Every how many levels you gain an extra block of jumping height while Crouching
	#Range: 0.0 ~ 1000.0
	levelsPerCrouchJumpBoost = 33.0
	#Maximum chance to save each point of fall damage (100 = no fall damage)
	#Range: 0.0 ~ 100.0
	maxFallSaveChance = 64.0
	#How much jump boost can you gain max (above 0.33 makes you take fall damage)
	#Range: 0.0 ~ 100.0
	maxJumpBoost = 0.33
	#How much speed boost you can get from Agility (100 = 100% vanilla + 100% = twice as fast max)
	#Range: 0.0 ~ 1000.0
	maxSpeedBoost = 100.0
	#How much your chance to save each point of fall damage increases per level (1 = 1% increase per Level)
	#Range: 0.0 ~ 100.0
	saveChancePerLevel = 64.0
	#Every how many levels you gain an extra block of jumping height while Sprinting
	#Range: 0.0 ~ 1000.0
	levelsPerSprintJumpBoost = 50.0
	#How much speed boost you get from each level (Incredibly sensitive, default 0.0005)
	#Range: 0.0 ~ 10.0
	speedBoostPerLevel = 5.0E-4

[Endurance]
	#Per how many levels you gain 1 Max Heart
	#Range: 0.0 ~ 1000.0
	levelsPerHeart = 10.0
	#How much endurance is max (100 = god mode)
	#Range: 0.0 ~ 100.0
	maxEndurance = 50.0
	#How many Max Hearts you can have (20 means 10 vanilla + 20 boosted)
	#Range: 0 ~ 1000
	maxExtraHeartBoost = 100
	#How much endurance you gain per level (1 = 1% per level)
	#Range: 0.0 ~ 100.0
	endurancePerLevel = 0.25

[Combat]
	#Per how many levels you gain 1 Extra Damage
	#Range: 0.0 ~ 1000.0
	levelsPerDamage = 20.0
	#How much extra damage can you get from the Combat skill max?
	#Range: 0.0 ~ 1000.0
	maxExtraDamageBoost = 100.0

[Smithing]
	#Should PMMO anvil handling be enabled? (xp rewards for repair, and also Enchantment handling) (some mod items break, if you experience lost enchantments, set this to false)
	anvilHandlingEnabled = true
	#Anvil combination limits enchantments to this level
	#Range: 0 ~ 255
	maxEnchantLevel = 255
	#Vanilla starts at 50, hence: (50 - [this] * level)
	#Range: 0.0 ~ 100.0
	anvilCostReductionPerLevel = 0.25
	#Bonus repair durability per level (100 = twice as much repair per level)
	#Range: 0.0 ~ 100.0
	anvilFinalItemBonusRepaired = 1.0
	#How many levels per each Enchantment Level Bypass above max level enchantment can support in vanilla
	#Range: 0 ~ 1000
	levelsPerOneEnchantBypass = 50
	#Anvil combination limits enchantments to max level set in this config
	bypassEnchantLimit = true
	#Max amount of levels enchants are able to go above max vanilla level
	#Range: 0 ~ 1000
	maxEnchantmentBypass = 10
	#Each Enchantment Save Chance per Level
	#Range: 0.0 ~ 100.0
	enchantSaveChancePerLevel = 0.9
	#What is the chance to Bypass a max enchant level (provided you got the skill to do so)
	#Range: 0.0 ~ 100.0
	upgradeChance = 50.0
	#Vanilla caps at 50, at around 30 vanilla you can no longer anvil the item again. allows unlocking infinite Anvil uses.
	#Range: 0 ~ 50
	anvilFinalItemMaxCostToAnvil = 10
	#Chance to not break anvil, 100 = twice the value, half the chance per Level.
	#Range: 0.0 ~ 100.0
	extraChanceToNotBreakAnvilPerLevel = 1.0
	#What is the chance to Reduce a level after a Upgrade chance fails (100 = everytime you fail bypass, enchant level goes down by 1)
	#Range: 0.0 ~ 100.0
	failedUpgradeKeepLevelChance = 50.0
	#Max Percentage chance to return each Enchantment Level
	#Range: 0.0 ~ 100.0
	maxSalvageEnchantChance = 90.0
	#false = Upgrade Chance if only rolled if you are trying to upgrade your item ABOVE vanilla max level. true = you ALWAYS have an upgrade chance level.
	alwaysUseUpgradeChance = false

[Swimming]
	#Underwater Nightvision Unlock Level
	#Range: 0 ~ 1000000
	nightvisionUnlockLevel = 25

[Fishing]
	#What is the chance on each successful fishing attempt to access the fish_pool
	#Range: 0.0 ~ 100.0
	fishPoolBaseChance = 0.0
	#What is the increase per level to access the fish_pool
	#Range: 0.0 ~ 100.0
	fishPoolChancePerLevel = 0.25
	#What is the max chance to access the fish_pool
	#Range: 0.0 ~ 100.0
	fishPoolMaxChance = 80.0

[Crafting]
	#How much xp should be awarded in Crafting for each item crafted? (Json Overrides this) (Set to 0 to disable default xp)
	#Range: 0.0 ~ 1000000.0
	defaultCraftingXp = 1.0
	#Should xp values for crafting be enabled? False means the default value is used
	xpValueCraftingEnabled = true

[Slayer]
	#How much slayer xp is awarded upon killing an aggresive mob by default
	#Range: 0.0 ~ 10000.0
	aggresiveMobSlayerXp = 0.0

[Hunter]
	#How much hunter xp is awarded upon killing a passive mob by default
	#Range: 0.0 ~ 10000.0
	passiveMobHunterXp = 0.0

[Taming]
	#How much xp should be awarded in Taming for Taming an animal? (Json Overrides this) (Set to 0 to disable default xp)
	#Range: 0.0 ~ 1000000.0
	defaultTamingXp = 0.0
	#Do players get xp for taming animals?
	tamingXpEnabled = true

